datasource:
  mysql:
    type: mysql
    host: 114.55.145.3
    port: 13306
    username: root
    password: wjyy26303
    database: rico
  mongodb:
    type: mongodb
    host: 114.55.145.3
    port: 17017
    username: root
    password: wjyy26303
    database: rico
